[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "8hMrECVej1KoLvygnfLytvGEuvQwGMT5jobXHkjjWpyS"

[programs.devnet]
escrow = "8hMrECVej1KoLvygnfLytvGEuvQwGMT5jobXHkjjWpyS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
